---

  - name: Add nginx repo
    tags: [yum, repos]
    copy: >
      src=nginx.repo
      dest=/etc/yum.repos.d/nginx.repo

  - name: Install nginx
    tags: yum
    yum: name=nginx state=installed

  - name: Put config and ssl
    include: "wwr-profile.yml"
    when: "'wwr-profile' in item"
    with_items: "{{group_names}}"
