---
- name: Find group path
  local_action: stat path=files/nginx/{{item}}
  register: file
  ignore_errors: True
  with_items:
    - "{{ group_names }}"

- debug: msg="{{item.stat.path}}"
  with_items:
    - "{{ file.results }}"
- name: Put group dir to server
  copy: >
    src=files/nginx/{{item.stat.path}}
    dest=/etc/nginx/pix
    owner=nginx
    mode=0644
  when: item.stat.exists
  with_items:
    - "{{ file.results }}"
