---

- name: Test group dirs
  stat: path={{ item }}/
  register: st
  with_items:
    - "{{ group_names }}"

- debug: msg="{{ st }}"

- name: Put files
  copy: >
    src= st.item/
    dest=/etc/nginx/pix
  when: st.stat.exists != `false`
