---
- name: Find group path
  local_action: stat path=files/nginx/{{item}}
  register: file
  ignore_errors: True
  with_items:
    - "{{ group_names }}"

- debug: msg="{{file}}"

- name: Put group dir to server
  copy: >
    src=nginx/sites/{{file.stat.path}}
    dest=/etc/nginx/pix
    owner=nginx
    mode=0644
  when: file.stat.exists
