---
- name: get file stat to be able to perform a check in the following task
  local_action: stat path=files/nginx/{{item}}
  register: file
  ignore_errors: True
  with_items:
    - "{{ group_names }}"

- debug: msg="{{file}}"
