---
- name: local test
  local_action: stat path=wwr-profile/
  register: local

- debug: msg="{{local}}"

- name: Test group dirs
  local_action: stat path={{ item }}/
  register: st
  with_items:
    - "{{ group_names }}"

- debug: msg="{{ st }}"

- name: local test
  local_action: stat path=wwr-profile/
  register: local
