---

- name: Test group dirs
  stat: path={{ item }}/
  register: st
  with_items:
    - "{{ group_names }}"

- debug: msg="{{ item.stat }}"
  with_items:
    - " {{ st.results }}"

- name: Put files
  copy: >
    src="{{ item.item }}"/
    dest=/etc/nginx/pix
  when: "{{ item.stat.exists }} != 'false'"
  with_items:
    - " {{ st.results }}"
