---

- name: Test group dirs
  local_action: stat path={{ item }}
  register: st
  with_items:
    - "{{ group_names }}"

- debug: msg="{{ st }}"

- debug: msg="{{ item.item }}, {{ item.stat.exists }}"
  with_items:
    - "{{st.results}}"

- name: test
  debug: msg="{{ item.item }}"
  when: "{{ item.stat.exists }}"
  with_items:
    - "{{st.results}}"
