---

- name: install git
  yum: name=git state=latest

- name: install ru.ugw.bioformer.server.tes.thrift
  yum: name=ru.ugw.bioformer.server.tes.thrift state=latest

- name: make ru.ugw.bioformer.server.tes.thrift symlink
  file: src=/usr/bin/ru.ugw.bioformer.server.tes.thrift dest=/usr/local/bin/ru.ugw.bioformer.server.tes.thrift state=link

- name: install maven
  yum: name=maven state=latest

- name: enshure work directories
  file: path='{{ profile_work }}' state=directory

- name: enshure dest directories
  file: path='{{ profile_dest }}' state=directory

- name: checkout GIT repository '{{ profile_server_repo }}' branch '{{ profile_server_branch }}' to '{{ profile_work }}'
  git:
    repo: '{{ profile_server_repo }}'
    dest: '{{ profile_work }}'
    version: '{{ profile_server_branch }}'
    update: yes
    force: yes
    accept_hostkey: yes

- name: build maven project
  command: mvn clean install -Pdev
  args:
    chdir: '{{ profile_work }}'

- name: copy jar to '{{ profile_dest }}'
  command: cp '{{ profile_work }}/server-common/target/server-common-1.0.2-SNAPSHOT-jar-with-dependencies.jar' '{{ profile_dest }}/server-common-1.0.2-SNAPSHOT-jar-with-dependencies.jar'