---

admins_keys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCzIj6zJP14o9h8x5xq5VonrH9L2pfEHQ655lcO58oVFe5mlPTk2K3jpErWyeJUq9Q8y4eXf+6U0VXdDn7e5IwYeKtV71ZSKThB7wsE4UrA8fWkYsasRxA9ibnlwjLdbhp82o2z31RNdf9qIt92Khtz90NMkOm8Ley43+1Peh23IK6zMq8XZRs3wnB93/hBZpDLsNYUD0JfS7/cuzih/6KdH5IART2tjofNKC1emBDM6iEvyXjK/Ad2oa9D0DKswrP/vs9qjfHNgH9VxHUCn+r5UA8pe8paoJxkfVT9briYCzxrx0GblqujNKgqmfpsZ2lLjHsH+UGjs/PyBz3iJmJb ilyakholinov@ilyas-mbp"
#revoke_keys:
#  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDAlpFLf5tYqE0jWhshtDAFRSJS1G3DvErgFyi6VSr3jKYUp9zGrBYO5Vpy1OuXaaz6ZdjlvUZl3Mdd9myY8wG1bC0ecPiTkumQnyUwrPkpm/Hwx1NgS9ej7UBvoFPswyqcklSxU7UAHBWiR4Yfy33Ht1wfwOm0Nv4bCOrM4/RY3dTA9li58a9dHnjteNJkY+wMwASakn/RVs7SusUPgmEZPwOsrvMS7qXvuN3apIgAYy1xa75AabmHfDS3V7ld9GsCjLXNlV1lA2kyGbmhXlxvnJhHyClvP7pMukYPIjRMwAFjr1YH9JFGMHrGdfN9BZHdIUwxhRTD8BL6SzoTsfb root@welch"


ntp_servers:
  - " 1.centos.pool.ntp.org"
  - " 2.centos.pool.ntp.org"
  - " 3.centos.pool.ntp.org"

ssh_pass_auth: "no"
ssh_port: 22
ssh_options:
  - "USEDNS no"
  - "KerberosAuthentication no"
  - "PubkeyAuthentication yes"
  - "UsePAM yes"
  - "GSSAPIAuthentication yes"
#  - "AuthorizedKeysCommand /usr/bin/sss_ssh_authorizedkeys"

def_pkgs:
    - ntp
    - vim
    - atop
    - unzip
    - screen
    - tmux
    - htop
    - gzip
    - zsh
    - telnet
