---
  - name: supervisord cobnfigure
    tags: [yum, supervisord]
    yum: name=supervisor state=installed

  - name: Enable service supervisord
    tags: [service, supervisord]
    service: name=supervisord enabled=yes

  - name: Put init.d file
    tags: [supervisord, file]
    copy: >
     src=supervisord
     dest=/etc/init.d/supervisord
     owner=root
     mode=0744

  - name: Put conf file
    tags: [supervisord, file]
    copy: >
      src=supervisord.conf
      dest=/etc/supervisord.conf
      owner=root
      mode=0744

  - name: test
    copy: >
     src={{group_name}}
     dst=/root/{{group_name}}
