---
  - name: supervisord cobnfigure
    tags: [yum, supervisord]
    yum: name=supervisor state=installed

  - name: Enable service supervisord
    tags: [service, supervisord]
    service: name=supervisord enabled=yes

  - name: Put init.d file
    tags: [supervisord, file]
    copy: >
     src=supervisord
     dest=/etc/init.d/supervisord
     owner=root
     mode=0744

  - name: Put conf file
    tags: [supervisord, file]
    copy: >
      src=supervisord.conf
      dest=/etc/supervisord.conf
      owner=root
      mode=0744

  - debug: msg="{{group_name}}"

  - name: test
    copy: >
     src="wwr-profile"
     dst=/root/{{ item }}
    with_items:
      - "{{group_name}}"

  - debug: msg=" {{src}}, {{dest}} "
