---
  - name: Sysctl rules
    tags: sysctl
    sysctl: name={{ item.name }} value={{ item.value }} sysctl_set=yes state=present reload=yes
    with_items:
      - "{{ sysctl_params }}"
    when: item is defined
