---

  - name: Check java
    command: 'rpm -qa'
    register: java_status

  - debug: msg="{{ java_status.stdout.find('jdk') }}"

  - name: Download java rpm
    tags: java
    get_url: >
      url={{java_url}}
      dest="/tmp/java.rpm"
      headers="Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"
    when: java_status.stdout.find('jdk') == -1 and java_url is defined

  - name: Java install
    tags: [java, install]
    yum: name=/tmp/java.rpm state=present
    register: java_install_status
    when: java_status.stdout.find('jdk') == -1

  - debug: msg={{java_install_status}}

  - name: Create java symlink
    file: src=/usr/java/latest/ dest=/usr/local/java8 state=link
