---
- include: CentOS6-repos.yml
  tags: yum
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

- include: CentOS7-repos.yml
  tags: yum
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: Install custom packages
  tags: yum
  yum: name={{ item }} state=installed
  with_items: "{{ def_pkgs }}"

- name: Add admins ssh keys
  tags: keys
  authorized_key: user=root key="{{ item }}"
  with_items:  "{{ admins_keys }}"

- name: Revoke admins ssh keys
  tags: keys
  authorized_key: user=root key="{{ item }}" state=absent
  with_items:  "{{ revoke_keys }}"

- name: Update root passwd
  tags: passwd
  user: name=root password="{{ root_passwd }}" update_password=always

- name: Add ntp config
  template: src=ntp.j2 dest=/etc/ntp.conf
  tags: time
  notify:
    - restart ntpd

- name: SSH config
  tags: ssh-config
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config owner=root mode=0600
  notify:
    - restart sshd

- name: Selinud disable
  tags: selinux
  selinux: state=disabled
  notify:
    - Restart server
    - Wait for server to restart



- name: Add resolv.conf
  tags: [dns, common]
  copy: src=resolv.conf dest=/etc/resolv.conf owner=root group=root mode=0644
