---
  - name: Add pam limits params
    tags: pam_limits
    pam_limits: >
         domain={{ item.domain | default("*") }}
         limit_type={{ item.limit_type }}
         limit_item={{ item.limit_item }}
         value={{ item.value }}
         dest={{ item.dest | default("/etc/security/limits.conf") }}
    with_items:
      - "{{ pam_limits_params }}"
    when: "{{ pam_limits_params }}" is defined
