---

- name: install ipa client
  yum: name=ipa-client state=installed
  when: ipa_role == "client"
  register: ipa_install

- shell: whoami
  register: usr

- debug: msg="{{ usr }}"

- name: Configure ipa client
  shell: >
     sudo
     ipa-client-install
     --mkhomedir  -U
     -p admin@{{ freeipa_domain }}
     -w P@ssw0rD
     --domain={{ freeipa_domain }}
     --realm={{ freeipa_domain }}
     --server={{ freeipa_server }}
     --hostname={{ ansible_fqdn }}.pix.lan
  when: ipa_install.changed
